### ISSUE TITLE
which is correct

### ISSUE THREAD

**Issue by Adeelp1** [Vibrant275/Prismio#6]
**Describe the bug**
[here](https://github.com/Vibrant275/Prismio/blob/master/tests/test.psmi#L10) class or clas

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Vibrant275** [comment]
Bro.
"class" is correct.
I have added 'clas' after that to build the test the parser properly.

Also. You can check the list of keywords In:
`src/keywords/keyword.h`

**Comment by Vibrant275** [comment]
When I will run :
run.bat in the tests folder the it should give an error for 'clas'

**Comment by Adeelp1** [comment]
thanks for the explanation

**Comment by Vibrant275** [comment]
Do you want my Instagram or whatsapp to contact. ?

**Comment by Adeelp1** [comment]
🤩yes, i want your instagram

**Comment by Vibrant275** [comment]
![Uploading Screenshot_20241020_181532.jpg…]()

**Comment by Vibrant275** [comment]
saksham.019
